version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: "circleci/node:12"
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: npm i -g coveralls
      - run: yarn
      - run: yarn test
      - run: cat coverage/lcov.info | coveralls
