version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: " circleci/node:10.16.3"
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: yarn
      - run: yarn test
